### ISSUE TITLE
Number of posts found: 0

### ISSUE THREAD

**Issue by naumanahmed19** [jamalneufeld/ghostHunter#11]
Hi,

Thanks for this plugin. I have added to my theme but getting some issue. Every time I search it return Number of posts found: 0 

here is a link to my blog 
http://ghost.xvelopers.com/voltov/

**Comment by naumanahmed19** [comment]
Got it fixed .

**Comment by orkhanalizade** [comment]
I have the same bug. How to fix it? @naumanahmed19

**Comment by talusnemeth** [comment]
@naumanahmed19 I've been having the same issue. It would be great if you could explain how you fixed it, or at least point others towards a solution. Thank you in advance.

**Comment by steven-tib** [comment]
Hi, I'm having the same issue, has anyone found a solution that you could share ? 
Thanks a lot

**Comment by Windyo** [comment]
Hi there!

Could you give me a link to your blog?
Thanks

Sent from BlueMail<http://www.bluemail.me/r>


On May 19, 2016, at 19:19, steven-tib <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, I'm having the same issue, has anyone found a solution that you could share ?
Thanks a lot

**Comment by zebheone** [comment]
I have same issue! http://twelvepurplepills.com/ thank you

**Comment by steven-tib** [comment]
@Windyo sorry I don't have deployed anything yet, just working locally. I will send you a link later cause I can't deploy right now for other reasons.
Maybe studying the case of @zebheone will help me as well. 
Thank you

**Comment by Windyo** [comment]
@steven-tib okay, let me know how it goes.

@zebheone : twelvepurplepills seems to work for me, but you're on the old version of Ghosthunter. I tried running a simple API call :
````js
	        $.get(ghost.url.api('posts', {limit: "all", include: "tags"})).done(function(data){
	        	searchData = data.posts;
            console.log(searchData);
          })
````
and I got an exception "ghost is not defined", which means that you probably haven't activated the ghost public API through the admin panel > Labs.
Oliver-flipper is not running at the moment, so I can't test it.

**Comment by Tamxaun** [comment]
@Windyo I had tried your test code and found an interesting thing, that on the error.hbs template the public api doesn't work )

**Comment by zebheone** [comment]
@Windyo ty for helping, the production blog is, as you mention, working. Now I got the dev env online I hope you can check it, I will try to keep it online for 8 hour. Public api on the dev env is active and I got the last ghostHunter code form git.

**Comment by Windyo** [comment]
Hi @Albi,

Following the link you posted for the dev env still returns an http 404.
Let me know where I can access it so I can troubleshoot this.

Kind regards,

**Comment by zebheone** [comment]
@Windyo Hi! it's up and running! still gives you 404? http://oliver-flipper.codio.io:3000/

**Comment by Windyo** [comment]
Works on mobile but not on my laptop fr some reason. I'll check on another connectio' in about 30 minutes or so.

**Comment by zebheone** [comment]
@Windyo thank you again! I think it's your connection, I can't connect to my blog dev env on my job network because of port blocking (but I don't get 404, website does not load). I can connect on mobile and home network

**Comment by Windyo** [comment]
@zebheone, I'm getting an error related to Jquery for some reason.
Could you try another CDN, or Zepto ? Thanks

**Comment by zebheone** [comment]
@Windyo Hi in my default.hbs I got 
```
<script type="text/javascript">  
  if (typeof jQuery == 'undefined') {
    document.write('<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js"></'+'script>');
  }
    </script>
```
I downloaded zepto and changed the code to 

> <script type="text/javascript" src= "{{asset "js/zepto.min.js"}}"></script>

but nothing is working

**Comment by Windyo** [comment]
@zebheone Yeah I tested with Zepto, that didn't change much, hence why I struck that part out.

In any case can you check if you specified to correct URL in your config.js file ? It probably doesn't specify the port.

**Comment by zebheone** [comment]
@Windyo wow now works! so stupid me! so I guess it will work in production! thanks for your time and help

**Comment by Windyo** [comment]
@zebheone glad to help. Closing this issue again. 
@steven-tib let me know how it all works out.

**Comment by duncancrozier** [comment]
Hi, I'm having a similar issue to this - the search function worked previously when it was on v0.4.0 when I first added it but now it doesn't return any results. I'm getting ghostHunter: init - so it seems to be partially working, also there are no JS errors in the console.
Any help would be appreciated please!
