### ISSUE TITLE
Include hit snippet in result

### ISSUE THREAD

**Issue by nknapp** [jamalneufeld/ghostHunter#15]
Is it possible to include the matching part of the blog post in the result?

**Comment by Windyo** [comment]
I've scratched my head a bit concerning this question and it seems to me that it's not doable for now.

https://github.com/olivernn/lunr.js/issues/200
https://github.com/olivernn/lunr.js/issues/97

To sum it up :
- lunr stems the words in the document
- returning a match or highlighting it will in fact be based on the stemmed token, not the searched word
- apart from the token itself, lunr stores no information about the search.

Tagged as won't do while waiting for new devlopments on this issue.

**Comment by jakey-wan-kenobi** [comment]
This seems like a pretty useful feature, and I don't think you'd need to rely on lunr to do it. Couldn't you just do this in the callback? Take the returned values, take the current input value, and then wrap where the matching substring in <b> tags?

**Comment by Windyo** [comment]
Hey,
you're more than welcome to give it a try :)
If you have any progress on this let me know.

Cheers

**Comment by magnusarinell** [comment]
Would be nice.
Cheers
