### ISSUE TITLE
Can it support the search for more languages? 

### ISSUE THREAD

**Issue by crawt** [jamalneufeld/ghostHunter#17]
Can it support the search for more languages? For example: Japanese, Korean Chinese.

**Comment by Windyo** [comment]
Well it's based on lunr.js, and this is a [known limitation](https://github.com/gilbitron/Raneto/issues/41)

@codepiano actually has a working solution for Chinese :
https://github.com/codepiano/lunr.js

Using [lunr-languages](https://github.com/MihaiValentin/lunr-languages) allows searching in German, French, Spanish, Italian, Japanese, Dutch, Danish, Portuguese, Finnish, Romanian, Hungarian, Russian, and Norwegian.

**Comment by Windyo** [comment]
Closing this issue further to our exchange.
I think it best to let people add languages when and if necessary ; I'll probably update the readme.md to reflect what was said here.
