### ISSUE TITLE
pubDate is only raw

### ISSUE THREAD

**Issue by mpancorbo** [jamalneufeld/ghostHunter#2]
Date is presented in a raw format (`pubDate` variable). I'd like a more pleasant one, ideally matching the way my theme outputs the date (and the installed locale).

I guess it is easy to accomplish for javascript programmers... but I'm not!

**Comment by ahmadajmi** [comment]
+!

**Comment by Windyo** [comment]
Closed via an enhancement made by @alavers on his fork, which was merged into master.
