### ISSUE TITLE
standalone version

### ISSUE THREAD

**Issue by Kikobeats** [jamalneufeld/ghostHunter#20]
Could be nice offer a version without dependencies inside, like:

ghostHunter.standalone.min.js → wihtout lunr
ghostHunter.standalone.min.js → with lunr

**Comment by Windyo** [comment]
That should be doable pretty quickly. I'll update the repo as soon as I can get to work on it.

**Comment by Kikobeats** [comment]
I have created a better project scaffold that contains this builds, preview in:

https://github.com/Kikobeats/ghostHunter

I'm put a little of work more and I will make a PR 😄

**Comment by Windyo** [comment]
Done.
