### ISSUE TITLE
cache index into browser storage

### ISSUE THREAD

**Issue by Kikobeats** [jamalneufeld/ghostHunter#22]
Instead of build index all the time, we can use browser storage (localStorage, SessionStorage, webSQL or IndexDB) as temporal cache

**Comment by Windyo** [comment]
This seems to have the same limitations as a server-side index, with the added problem that all users will have a cached version of it, and the the blog host has no way to force a refresh centrally.

Either we suppose a time-based index refresh, which means that if you have a very active blog, a lot of content could not be indexed, or we consider a hash-check between the two indexes, which still implies building the index.

Maybe I'm wrong of course, would love to hear your thoughts on this.

**Comment by ItsMohammad** [comment]
I think the server-side cache would be better since you could make it so every time someone creates a new post the old cache is restart since most people don't make those many decisions.
