### ISSUE TITLE
Search static page

### ISSUE THREAD

**Issue by chenzhepeter** [jamalneufeld/ghostHunter#24]
Apparently it cannot search static page. Is this a known issue? Thanks!

**Comment by Windyo** [comment]
Hmmm,  according to the API docs (here) [https://github.com/TryGhost/Ghost/wiki/%5BWIP%5D-API-Documentation] it seems that posts which are static pages are not queried by the API call by default. 

I'll look into adding an option for this in the ghosthunter vars.

**Comment by Windyo** [comment]
@chenzhepeter Okay, if you replace 
````js
	        $.get(ghost.url.api('posts', {limit: "all", fields: "id,title,meta_description,markdown,created_at,url", include: "tags"})).done(function(data){
````
with
````js
	        $.get(ghost.url.api('posts', {limit: "all", filter: "(page:true,page:false)", fields: "id,title,meta_description,markdown,created_at,url", include: "tags"})).done(function(data){
````

in the main .js, it should return what you expect.

I will update ghosthunter itself once I can give the possibility to users to include or exclude the static pages from the options menu..

**Comment by Windyo** [comment]
@chenzhepeter Hey, this has been delivered in the develop branch on my fork. I'll merge it once I finish testing it ; if you want to give me a hand for the tests please do.
