### ISSUE TITLE
Cyrillic search

### ISSUE THREAD

**Issue by bloadvenro** [jamalneufeld/ghostHunter#27]
Hello and thank you for your work!

I've installed ghostHunter on my fresh ghost blog, but soon I noticed, that only english matches show up in onKeyUp frame.

**Comment by Windyo** [comment]
Hi there, and thanks !

This actually is a bug in lunr.
The [https://github.com/olivernn/lunr.ru.js](russian implementation) of lunr seems quite dead, so I would probably use the workaround [https://github.com/olivernn/lunr.js/issues/42](listed in lunr issue 42) for the moment.
