### ISSUE TITLE
{{prettyPubDate}} not resolved in results output

### ISSUE THREAD

**Issue by gaco** [jamalneufeld/ghostHunter#29]
Renaming prettyPubDate to pubDate should work.

**Comment by Windyo** [comment]
PubDate is used as a variable by prettypubdate
I saw your comment on the pull, going to try and close this in the following weeks.

**Comment by Windyo** [comment]
funnily enough I've tried to repro

**Comment by NerdOfLinux** [comment]
I know this thread is old, but I have the same issue with the latest version.

**Comment by resting** [comment]
Just tried and I'm this problem too.

**Comment by bobhy** [comment]
If that's to be the resolution, the default results template ought to be fixed before closing this bug.
