### ISSUE TITLE
Search function update assistance.

### ISSUE THREAD

**Issue by ItsMohammad** [jamalneufeld/ghostHunter#30]
Hello, could someone update my Search function to support the latest ghosthunter? The goal of updating my search function is so users can be able to type anything in the Search bar and not be limited to only 15 responses. Plus, It would be great if when someone does update my Search function they edit any other files that could improve the search experience for users.

My theme:
Email me at support@IAskMuslim.com for the theme link.

My website:
https://iaskmuslim.com

PS:
Sorry, If I made you mad @Windyo <3. I can be a little inpatient time to time but it would mean a lot if you took the time out of your day to help me with this problem. Lastly, I tried doing this myself but I could not get it to work and I contact the dev of the theme but he will not update he said. And is it necessary for me to turn on Public API?

**Comment by ItsMohammad** [comment]
I'm going to try following this guide and see how it goes. 
https://cmatskas.com/add-search-to-your-ghost-blog-with-lunr-js-and-ghosthunter/

**Comment by Windyo** [comment]
Hey,
I'm kind of bogged up for the moment, so I can't really look into this deeply.

Anyway the search.hbs isn't what you need to update (assuming you see the search bar on your site, which I am assuming in the case seeing as your reported incomplete search results).
In your theme there's a file called app.js. I haven't looked into exactly what it contains, but this is where the theme developer stored the ghosthunter.js logic.

You need to find the old ghosthunter code in that file, delete it, and replace it with the new version. And make a backup first, of course...

**Comment by ItsMohammad** [comment]
Okay, I updated the "jquery.ghostHunter.min" in the assets/js/scripts folder. I have no idea what the old ghost hunter code look like in the app.js file and I don't know any javascript editors too.

app.js file:
https://drive.google.com/file/d/0BwT9NUByykAaczNhQWxTdHRuY2s/view?usp=sharing

**Comment by ItsMohammad** [comment]
If you could update my app.js file to the latest code of your amazing plugin that would be helpful since I don't know what to update.

**Comment by Windyo** [comment]
The app.js file is minifed and probably autogenerated by gulp or something. Check your theme doc to see if they gave any specific instructions concerning this.

**Comment by ItsMohammad** [comment]
Does this look better?
http://pastebin.com/Y38pmpBg

**Comment by ItsMohammad** [comment]
Every time I update it the search icon does not show up on the sidebar anymore.

**Comment by ItsMohammad** [comment]
I'm just going to wait until you have some time to help me with it  since I keep breaking my site.
http://prntscr.com/d7wrcp

**Comment by Windyo** [comment]
Not going to lie: I probably won't have time to check this until a couple of weeks at earliest.

What you could do as a temporary workaround is this:
- Take your app.js file, open it, delete the contents
- for each file in the /assets/js/src folder, copy the entire file and paste it ito the now blank app.js.
- the app.js file now contains the full contents of all files in the SRC folder
- [minify the file](https://jscompress.com/)
- replace the app.js file with this new one you just created.

If you give it a go today I can take a minute to check what's going wrong, if it does go wrong. But there is no reason for it to.

**Comment by ItsMohammad** [comment]
Okay, I'm going to try that now.

**Comment by ItsMohammad** [comment]
I did what you said but now the search icon with all my social media icons are not showing up anymore.

Current theme: 
https://drive.google.com/drive/folders/0BwT9NUByykAacDFRcGM2Y0VsTXc?usp=sharing

New file:
http://pastebin.com/wajVM4f6

**Comment by Windyo** [comment]
Yeah I see that. Give me the original app.js file again ?

**Comment by ItsMohammad** [comment]
This is the file that's not minify.
http://pastebin.com/Y38pmpBg

**Comment by ItsMohammad** [comment]
This is the file that is minified.
http://pastebin.com/TRCC1Axi

**Comment by Windyo** [comment]
The app.min.js contains more code than what is in the source folder....
Try this ?
http://pastebin.com/J6YaTuFK

**Comment by ItsMohammad** [comment]
It shows now but doses work.
https://iaskmuslim.com/

**Comment by ItsMohammad** [comment]
Wait, should I update any files in the scripts folder?

**Comment by Windyo** [comment]
Let me take a moment here to say I hate your theme developer.

"ghost is not defined" generally means you haven't allowed the ghost API to run.

**Comment by ItsMohammad** [comment]
Wait, I should turn on Public API?

**Comment by Windyo** [comment]
Yes

**Comment by ItsMohammad** [comment]
WORKS NOW!

**Comment by ItsMohammad** [comment]
OMG, THANK YOU SO MUCH!

**Comment by ItsMohammad** [comment]
Thank you so much for helping me with this!

**Comment by Windyo** [comment]
NP. but I REALLY hate your theme dev. Who gives a script source with missing features FFS.

Anyway, ghosthunter is configured by default in your blog, so it's optimized for smaller data sets.
You should really take the time to read the doc to learn how to customize it to your use and optimize performance.

FYI the ghosthunter code is now the same one from this repository so you can find it with CTRL+F quite easily.

**Comment by ItsMohammad** [comment]
Thanks.

**Comment by ItsMohammad** [comment]
Where can I find the GhostHunter doc?
