### ISSUE TITLE
Is there a way to trigger keyup event when page loaded?

### ISSUE THREAD

**Issue by taechemist** [jamalneufeld/ghostHunter#31]
right now, I have search page with default value in search box. I want to trigger the event using .keyup(), but it doesn't seem to work. Only show "Number of posts found: 0". Any idea?

**Comment by Windyo** [comment]
You're have to rewrite part of the logic.

You can use the onpageload option to trigger the index being built on page load, but if your text is already present it will try to trigger a search while the index is still being built (that is the main performance problem right now as blog size goes up), which will result in 0 results.

You should use the OnPageLoad option, and add an event to trigger the search once that routine has completed.

**Comment by taechemist** [comment]
Good idea, Thank you.
