### ISSUE TITLE
{{Description}} is not out putting in search results

### ISSUE THREAD

**Issue by Samrura** [jamalneufeld/ghostHunter#32]
```
var searchField = $("#search-field").ghostHunter({
   results   : "#results",
   onKeyUp         : true,
   onPageLoad      : true,
   result_template : "<a href='{{link}}'><h2>{{title}}</h2><h4>{{pubDate}}</h4> <p>{{description}}</p></a>"
 });
```
I added that and all I get is the **link** **title** and **date** , no description? 

and I had a look in the ghost api docs  https://api.ghost.org/docs/post

but all I see for the post json object is 

```
post: {
    id: 1,
    uuid: "ec630e45-3342-4d7f-a24c-e448263c975b",
    title: "Welcome to Ghost",
    slug: "welcome-to-ghost",
    markdown: "You're live! Nice.",
    html: "<p>You're live! Nice.</p>",
    image: '/content/images/2014/12/my-image.png',
    featured: false,
    page: false,
    status: 'published',
    language: "en_US",
    meta_title: null,
    meta_description: null,
    author_id: 1,
    created_at: "2014-04-15T12:36:28.353Z",
    created_by: 1,
    updated_at: "2014-04-15T12:36:28.353Z",
    updated_by: 1,
    published_at: "2014-04-15T12:36:28.363Z",
    published_by: 1
}
```

going to have a play around and change description to html  but  if it's something i'm doing wrong some help would be great

**Comment by sameergoyal** [comment]
It seems that ghosthunter is parsing meta_description for creating the description of a post. If your posts have meta_description populated, you should see {{description}} getting populated.

**Comment by Windyo** [comment]
Yeah the "description" could be horrendously long, so we're using meta_description for it.
Otherwise people would have entire articles populating in the search template, and this was considered a bug.

I would simply advise you to populate meta_description on your articles_ otherwise you may change occurences of meta_description to something more fitting to your needs.
