### ISSUE TITLE
ghost is not defined

### ISSUE THREAD

**Issue by ubuntutest** [jamalneufeld/ghostHunter#33]
Hello,
I've added it inside body in default.hbs:

```
 <form>
        <input id="search-field" />
        <input type="submit" value="search">
        <input type="button" value="clear" onclick="clearResults();" />
      </form>

      <hr />
        
      <section id="results"></section>

      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
      <script src="js/jquery.ghostHunter.js"></script>

      <script>

        var searchField = $("#search-field").ghostHunter({
                            results     : "#results",
                            rss         : "rss.xml",
                            //Enable the "search as you type" by uncommenting the following line
                            //onKeyUp   : true
                          });

        function clearResults() {
          searchField.clear();
        }

      </script>
```

But i'm getting the following error:

```
Uncaught ReferenceError: ghost is not defined
    at Object.loadAPI (jquery.ghostHunter.js:110)
    at HTMLInputElement.<anonymous> (jquery.ghostHunter.js:76)
    at HTMLInputElement.dispatch (jquery.min.js:5)
    at HTMLInputElement.v.handle (jquery.min.js:5)
```

How to fix it?
Thank you

**Comment by Windyo** [comment]
You haven't activated the public API in the ghost settings 😉

Sent from BlueMail<http://www.bluemail.me/r?b=9184>
On Mar 13, 2017, at 23:29, ubuntutest <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,
I've added it inside in default.hbs:

 <form>
        <input id="search-field" />
        <input type="submit" value="search">
        <input type="button" value="clear" onclick="clearResults();" />
      </form>

      <hr />

      <section id="results"></section>

      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
      <script src="js/jquery.ghostHunter.js"></script>

      <script>

        var searchField = $("#search-field").ghostHunter({
                            results     : "#results",
                            rss         : "rss.xml",
                            //Enable the "search as you type" by uncommenting the following line
                            //onKeyUp   : true
                          });

        function clearResults() {
          searchField.clear();
        }

      </script>


But i'm getting the following error:

Uncaught ReferenceError: ghost is not defined
    at Object.loadAPI (jquery.ghostHunter.js:110)
    at HTMLInputElement.<anonymous> (jquery.ghostHunter.js:76)
    at HTMLInputElement.dispatch (jquery.min.js:5)
    at HTMLInputElement.v.handle (jquery.min.js:5)


How to fix it?
Thank you

**Comment by ubuntutest** [comment]
Thanks for answer, i have this problem now:

`XMLHttpRequest cannot load https://mydomain/ghost/api/v0.1/posts/?limit=all&include=tags&client_id=ghost-frontend&client_secret=57401ec52288. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mydomain' is therefore not allowed access.`

**Comment by Windyo** [comment]
You didn't replace "mydomain" with your domain.

Sent from BlueMail<http://www.bluemail.me/r?b=9184>
On Mar 14, 2017, at 11:13, ubuntutest <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for answer, i have this problem now:

XMLHttpRequest cannot load https://mydomain/ghost/api/v0.1/posts/?limit=all&include=tags&client_id=ghost-frontend&client_secret=57401ec52288. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mydomain' is therefore not allowed access.

**Comment by ubuntutest** [comment]
Dude, i changed the address to mydomain in here to hide it, for privacy. (btw i solved it by adding headers in nginx.conf)
Btw  read my edits, I modified my previous post, u hevnt noticed it, probably because you answered via email.

`Thanks for answer, i have this problem now:

{{prettyPubDate}}

And in console, if i click on it:

Uncaught TypeError: $(...).ghostHunter is not a function at (index):102`

**Comment by Windyo** [comment]
Haha sorry. I'm on the road ATM, just trying to answer how I can.

I'll check it out once I have access to a comp then.

If generally if it says ghosthunter is not a function that means the . js isn't correctly referencef in the page.
Sent from BlueMail<http://www.bluemail.me/r?b=9184>
On Mar 14, 2017, at 12:17, ubuntutest <notifications@github.com<mailto:notifications@github.com>> wrote:

Dude, i changed the address to mydomain in here to hide it, for privacy. (btw i solved it by adding headers in nginx.conf)
Btw read my edits, I modified my previous post, u hevnt noticed it, probably because you answered via email.

`Thanks for answer, i have this problem now:

{{prettyPubDate}}

And in console, if i click on it:

Uncaught TypeError: $(...).ghostHunter is not a function at (index):102`

**Comment by ubuntutest** [comment]
Thanks for the help then..

The js  is correctly loaded, the search form works correctly, otherwise it would not work.
But in addition to the search result also get this "{{prettyPubDate}}" in homepage, dont know why.

drive carefully :)

**Comment by ubuntutest** [comment]
So any idea how to solve this ?
http://imgur.com/a/rKy2S

**Comment by ubuntutest** [comment]
Solved by deleting {{prettyPubDate}} from

	`	result_template 	: "<a href='{{link}}'><p><h2>{{title}}</h2></p></a>",`


in jquery.ghostHunter.js
