### ISSUE TITLE
How to limit the number of fields queried?

### ISSUE THREAD

**Issue by ubuntutest** [jamalneufeld/ghostHunter#39]
Hello all

I can not limit the number of search results and create a link that makes a redirect and show all the results.
For example, the search engine at: https://docs.ghost.org/docs

Is there any parameter to set?

**Comment by Windyo** [comment]
Hi there - The current state of GhostHunter does not do this by default.

If you want to limit the number of posts queried, you can change the limit:all to limit:yournumber, which will in fact limit the umber of posts returned by your blog.

When on your main subpage, you shuold then use limit:all to unsure everyresult is displayed.

**Comment by ubuntutest** [comment]
As you said, if you set a limit: 3, I do not limit the three-post view, but limit the search to the last three posts, unfortunately it is not what I'm trying to do

**Comment by ubuntutest** [comment]
Solved it, u can delete, thanks
