### ISSUE TITLE
Variable "tag" and Empty search-field

### ISSUE THREAD

**Issue by ubuntutest** [jamalneufeld/ghostHunter#40]
"The result template has access to these variables: title, description, link, pubDate."
 Is possibile somehow to acess "tags" too?

My main problem is another, i would like to show "all results" when search-field is empty.
I mean,
after I search for something I would like that by deleting progressively  the value in the input, I show all the posts, is it possible?

**Comment by fbennett** [comment]
Pull request #45, currently under review, includes a ``tags`` field in the return, which has all tags as a single comma-delimited string. (If you wanted a subset of the tags, or wanted to treat each as a unit, you would have to do some post-processing of them somehow.)

You can restore the page when the search field is empty outside of ghostHunter, by placing a JQuery listener tied to the ``change`` event on the search input field that checks the ``value`` property (not the attribute). Depending on how your pages are laid out, you might need to do a little reorganizing, to be sure that the original page content is hidden but not clobbered during search.

**Comment by Windyo** [comment]
Closed further to release
