### ISSUE TITLE
Smoother search-as-you-type updates

### ISSUE THREAD

**Issue by fbennett** [jamalneufeld/ghostHunter#43]
ghostHunter currently updates the list of search hits by clearing and restoring the list. Since many Ghost styles do quite a bit of display formatting, there is pretty severe jitter effect when ``onKeyUp`` is enabled. It should be possible to update the list using a Levenstein-distance tool, applying just the changes necessary in the current (last-search-result) display to make it reflect the incoming data array. I'll see if I can get this working, and if it works out, post a pull request after #42 has cleared.

**Comment by fbennett** [comment]
This worked out very nicely. You can try out the feel of it at https://our.law.nagoya-u.ac.jp/alumni/

**Comment by fbennett** [comment]
@Windyo I'm filed a pull request for the second round of changes. There are merge conflicts, I hope it's not too much of a headache at your end to resolve them.

**Comment by fbennett** [comment]
(fixed the conflicts, of course, and PR is now #45)

**Comment by Windyo** [comment]
closed after merge
