### ISSUE TITLE
results.size is not a function

### ISSUE THREAD

**Issue by astab** [jamalneufeld/ghostHunter#46]
Hi there,

thanks you for this plugin. 
I have updated it to version 0.5.0 in my theme but when trying to search I'm getting the following error:

Uncaught TypeError: results.size is not a function at Object.<anonymous> (jquery.ghosthunter.js?v=79caedeb82:3478)

HTML:

```
<form class="search-form">
	<input type="text" id="search-field" class="search-field" placeholder="Type your keywords&hellip;" />
	<input type="submit" class="search-submit" value="Search" />
</form>
<div id="search-results" class="search-results"></div>
```

jQuery code:

```
var searchField = $('#search-field').ghostHunter({
	results : "#search-results",
	onKeyUp : true
});
```

Can you help to fix it?
Thank you.

**Comment by Windyo** [comment]
Hey!

Weird, didn't encounter this un my tests. Can you share your results template?

Cheers

**Comment by astab** [comment]
I've tried not setting up the option and leaving the default value, as in the code in my previous comment. And also, tried to set the result_template option like this:

```
result_template : '<a id="gh-{{ref}}" class="gh-search-item" href="{{link}}"><div class="result-title">{{title}}</div><div class="result-date">{{prettyPubDate}}</div></a>'
```

**Comment by astab** [comment]
Also, forgot to mention that I am using jQuery 3.3.1.

**Comment by fbennett** [comment]
Ah. ``$().size()`` [is deprecated](http://api.jquery.com/size/). Looks like we can just use ``$().length`` there.

**Comment by astab** [comment]
I have tried to replace `$().size()` with `$().length` but it didn't helped.

**Comment by astab** [comment]
Changing `$().size()` to `$().length` fixed this. Thank you, @fbennett !

I am also getting the following error when trying to clear search results with `searchField.clear();` :

Uncaught TypeError: Cannot read property 'val' of undefined
    at Object.clear (jquery.ghosthunter.js?v=79caedeb82:3532)
    at HTMLButtonElement.<anonymous> (custom.js?v=79caedeb82:87)
    at HTMLButtonElement.dispatch (jquery-3.3.1.min.js:2)
    at HTMLButtonElement.y.handle (jquery-3.3.1.min.js:2)

Could you please help?

**Comment by Windyo** [comment]
Should we update that directly in the source repo then ? if we start requiring specific versions of jQuery things are going to get interesting.

**Comment by Windyo** [comment]
After checking the docs it's been deprecated since 1.8... changed, issue closed.

**Comment by gllmhyt** [comment]
Even with commit 7e0f675 results are broken:

```
TypeError: results.length is not a function (jquery.ghosthunter.js:3478:15)
```

My config:
* Ghost 1.21.3
* jQuery v3.2.1

**Comment by Windyo** [comment]
... I did a typo when committing 7e0f675 
I did a hotfix just now but I won't be able to test until this weekend. If you've got free time, try the latest commit, otherwise revert to 0.4.0 until I finish ironing this out.

Sorry about this

**Comment by gllmhyt** [comment]
@Windyo At least with 7a058da it displays results, that's all I need for now, thank you for that quick fix. ;)

**Comment by Windyo** [comment]
Considering this closed seeing as I use that version also and I haven't seen any issues
