### ISSUE TITLE
Show in result_template

### ISSUE THREAD

**Issue by ubuntutest** [jamalneufeld/ghostHunter#51]
I'm showing results in a custom result using {{title}} and {{description}}, is it possible to show tags in this way? {{tag}}, at the moment I think it is not possiible, could it be an upcoming implementation?

**Comment by fbennett** [comment]
In the current version tags are available, as an array, under the "tags" key.

**Comment by ubuntutest** [comment]
Ah ok, then I'll have to wait, as I told you, I use an old version. Thank's for your job

**Comment by ubuntutest** [comment]
I do not know the real difficulty in implementing a new variable. Probably the easiest thing would be to render only the first tag, certainly with the ability to click on them and open the page around the tag. Like the default casper template, in post-cards.hbs, we have {{primary_tag.name}

**Comment by fbennett** [comment]
I'll see what I can do. Maybe offering the option of the first, or all tags will be nice for flexibility.

**Comment by Windyo** [comment]
^ If you want to try your hand at it you're more than welcome to.

However, remember that Ghost are still working on their "App" api, that will make most of this redundant. Granted, it's been in the works for more than two years, but still.

Building to extend the standard string replacement methods seems like a fair amount of work for minor long-term improvements.

**Comment by Windyo** [comment]
Closed because stale and I don't think this will be a core focus.
