### ISSUE TITLE
How to get more data? Such as image, content and more

### ISSUE THREAD

**Issue by QingShui23** [jamalneufeld/ghostHunter#56]
怎么获取更多数据？比如image、content等等
How to get more data? Such as image, content and more？
我想在搜索结果中展示文章焦点图
I want to show the focus image of the article in the search results

**Comment by Windyo** [comment]
You need to add the data to the API call we are doing in `$.get(ghost.url.api('posts',obj)).done(function(data){`

and add that to the results template/index depending on what you want to do.

**Comment by QingShui23** [comment]
I mean to show in the search results of ghosthunter template
