### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by duncancrozier** [jamalneufeld/ghostHunter#57]
#11 
Hi, I'm having a similar issue to issue 11 - the search function worked previously when it was on v0.4.0 when I first added it but now it doesn't return any results. I'm getting ghostHunter: init - so it seems to be partially working, also there are no JS errors in the console.
Any help would be appreciated please!

**Comment by Windyo** [comment]
That's weird. Can you dump your ghost Version? Latest GhostHunter only works on the newer API of ghost

Sent from BlueMail<http://www.bluemail.me/r?b=13037>
On May 19, 2018, at 15:24, Duncan Crozier <notifications@github.com<mailto:notifications@github.com>> wrote:

#11<https://github.com/jamalneufeld/ghostHunter/issues/11>
Hi, I'm having a similar issue to issue 11 - the search function worked previously when it was on v0.4.0 when I first added it but now it doesn't return any results. I'm getting ghostHunter: init - so it seems to be partially working, also there are no JS errors in the console.
Any help would be appreciated please!

**Comment by duncancrozier** [comment]
Hi - thanks for the answer... I think I'm on 1.19.2
![screen shot 2018-05-19 at 19 34 37](https://user-images.githubusercontent.com/10114419/40271298-b9b49070-5b9b-11e8-8f7b-53e149aa1a81.png)

**Comment by duncancrozier** [comment]
Not sure why this is closed??? I didn't close it!
Can we re-open it please!
Cheers

**Comment by duncancrozier** [comment]
@Windyo not sure why this ticket is closed, I don't recall closing it!
Any thoughts on a solution?
Cheers
