### ISSUE TITLE
Multiple distinct indexes in different areas of a site?

### ISSUE THREAD

**Issue by TaoK** [jamalneufeld/ghostHunter#58]
Hi, I'm using ghost in a maybe-unusual way, with multiple substantially-distinct sets of stories in a single ghost instance.

Different sets of stories coexist and display in different areas of the site, with tags controlling what shows where.

In my case I happen to be implementing a multi-language site (under a single ghost instance), but I could imagine other use-cases for this type of tag-based partitioning.

So, what I'm wondering is what it would take to support "filtered indexing" in ghosthunter, whereby I would pass in, at initialization time, the tag filters that I want passed into the ghost API.

In my case I would only ever want one search on any one page of the site, so I don't need to worry about encapsulating configuration/initialization properties that are currently "global" in the ghosthunter plugin object.

As far as I could tell this should be very straightforward, with only two important changes to be made:

1. Add support for passing the filter in, and having it be passed through to the ghost API call in indexing

2. Ensure that the localstorage key (at index setting and retrieval time) is updated to include the filter key (or some other explicitly passed in identifier).

Is there anything else I'm clearly missing in this proposed scheme?

**Comment by Windyo** [comment]
To be honest I don't have the technical expertise needed to answer your question.

As said in another question, watch out for Tag filtering : you can check it out at https://api.ghost.org/ but the ghost api is rather unstable at times, and some operations are not doable together (eg query authors and limit fields returned in a single call didn't work for a long, long time)

At its core, GH is just a lunr search running on an index built from an API call, so if you build multiple indexes and call them appropriately based on input from a user, I don't see much of a reason this wouldn't work.
