### ISSUE TITLE
Search results disappeared in 0.4.1 and duplicated in 0.5.0

### ISSUE THREAD

**Issue by huydhoang** [jamalneufeld/ghostHunter#61]
Hi, I have tried v0.3.5, 0.4.1, and 0.5.0 and noticed strange behaviors since version 0.4.1:
- v0.5.0: search results duplicated every time a key is pressed, even with arrow keys
- v0.4.1: no search results 
- v0.3.5: results displayed normally, but only words in the title are parsed, not the post content

Syntax used:
```
$(function() {
    
    /* search results */
    var res = {}
    res.body = '\n  <a href="{{link}}">\n    <span>{{title}}</span>\n    <span">{{pubDate}}</span>\n  </a>';
    res.info = '<p>Found {{amount}} stories</p>';
    
    
    $("#search-field").ghostHunter({
        results: "#results",
        onKeyUp: true,
        result_template: res.body,
        info_template: res.info,
        displaySearchInfo: true,
        zeroResultsInfo: false,
        includepages: false,
        onPageLoad: true
    });
});
```

Jquery version: 3.3.1 latest

Is this a bug or am I doing anything wrong?

**Comment by Windyo** [comment]
That's strange, I use ghosthunter myself, and while I admit v 5.0 is a tad buggy I haven't had any issues with 4.1...

Does the console show anything ?

**Comment by hystcast** [comment]
I had the duplication issue in a template I was using. 

Check the result_template you're using. The template needs to have an enclosing tag (<div> <span>), with a unique ID (the suggestion was to use {{ref}}), and a class of gh-search-item. 

After I changed these the results were no longer duplicating.

**Comment by huydhoang** [comment]
> That's strange, I use ghosthunter myself, and while I admit v 5.0 is a tad buggy I haven't had any issues with 4.1...
> 
> Does the console show anything ?

Sorry for taking so long. I stopped using ghost for a while and now I'm deploying a fresh new one. As I remember, there wasn't anything showing in the console. But let's see. I'll look into this again.

**Comment by Windyo** [comment]
Alright I'll close this up. FYI I just released a minor version.
