### ISSUE TITLE
Feature Request search by date

### ISSUE THREAD

**Issue by saschalalala** [jamalneufeld/ghostHunter#63]
Hey, thanks for this really nice addon, it works really good for me.

One thing though that I would love to have is the ability to search by date, e.g. with a search query like `2018-05` which then finds all posts that were created in May 2018. Is something like this doable with your current application?

**Comment by Windyo** [comment]
If you add the date to the index it should be searchable with lunr though I'm quite sure the way it tokenizes search terms will have strange effects.

**Comment by Windyo** [comment]
Closed as stale.
