### ISSUE TITLE
`.clear()` throws Uncaught TypeError: Cannot read property 'val' of undefined

### ISSUE THREAD

**Issue by resting** [jamalneufeld/ghostHunter#64]
In `ghosthunter.js`,
```
clear       : function(){
      $(this.results).empty();
      this.target.val("");
    },
```
`this.target` is undefined.

Tried to fix it by adding `this.target = target` after line:176 of `ghosthunter.js` but got a slightly different compiled version in `dist` folder than the one cloned.

**Comment by Windyo** [comment]
Closed as duplicate. Fixed with newest release.
