### ISSUE TITLE
Special Characters on Search

### ISSUE THREAD

**Issue by javierencalada** [jamalneufeld/ghostHunter#65]
Hi!, i want to know if there is any possibility to use special characters like Russian Language, for example: https://blog.s10.run/ this site is using Russian and when i fill the search field always throw 0 results.

But if i use standard characters like "Suunto" http://prntscr.com/jzp12e works as expected.

I tried installing Lunr and multiple languages support, but it's not working at all, did i miss something?

Thank you!

**Comment by Windyo** [comment]
Hey,

not really, as it relies on lunr. there's a few closed issues where we go over the challenge of using chinese for example.

**Comment by fitwist** [comment]
Are there any changes? I've integrated gH on my website, but cyrillic symbols are still not supported.
