### ISSUE TITLE
Search after the site is fully loaded

### ISSUE THREAD

**Issue by ubuntutest** [jamalneufeld/ghostHunter#69]
Ghosthunter seems to work correctly,
but if I start searching immediately when the page loads, I will not see any results. 
How can I start the search only Ghosthunter seems to work correctly, but if I start searching immediately when the page loads, I will not see any results. How can I start the search only after the site is fully loaded or after the ghosthunter is ready? thank you or after the ghosthunter is ready? 
thank you

**Comment by Windyo** [comment]
@ubuntutest new versions should take care of this already. Otherwise you would need to call the JS function after document.ready.
