### ISSUE TITLE
Use the full RSS feed

### ISSUE THREAD

**Issue by MaluNoPeleke** [jamalneufeld/ghostHunter#7]
One question related to RSS: is it possible to use the full RSS feed instead of only the first page for the searchable content? /rss/ displays only a part of the published blog post, you can see the rest with /rss/2, /rss/3, ...

**Comment by nv1t** [comment]
You will have the same Problem with the Ghost API. Currently they are doing Pagination as well.
What about loading the stuff into local storage/session storage.
Therefore, you only load it once, but can use it after a page reload :)

**Comment by Windyo** [comment]
@nvt1 Actually you can query all the posts by referencing limit:all in your api query. :)

**Comment by Windyo** [comment]
Ghosthunter now uses the ghost api and queries all posts.
Closing this issue to reflect that, let me know if you have any other problems.
