### ISSUE TITLE
Question: search results page

### ISSUE THREAD

**Issue by etanb** [jamalneufeld/ghostHunter#70]
Hi there,

Is it possible to have a separate search results page? Was wondering if we could, upon submittal of search query, go to a new list view page with the search results instead of inline on the current page.

**Comment by Windyo** [comment]
Would be hard - you'd have to pass the results that GH generates to a constructor that will build the page. To be honest if you could do that you probably wouldn't rely on GH to fetch the results in the first place.

Cheers ;)
