### ISSUE TITLE
Search not appending to query

### ISSUE THREAD

**Issue by twigs67** [jamalneufeld/ghostHunter#71]
It doesn't seem to be working after following the basic setup. I've ensured the repo was installed correctly and that ghosthunter.js is being loaded after jquery. I've tried it on a few different themes.

When I enter text into the search field and hit enter, it reloads the page with an empty query param. 
So I believe the issue is that it is not grabbing the search value as no query params are being passed to the url.

**Comment by Windyo** [comment]
Couleur you post a link to the blog ? Because normally pressing enter does not reload anything as a reload would effectively lose the information passed to lunr

Anon Ymous

________________________________

**Comment by twigs67** [comment]
@Windyo I'm testing it locally. I've uploaded the test theme [here](https://github.com/twigs67/ghostHunterTest). You can see where I added the lines based off of the Basic Setup at the bottom of default.hbs

**Comment by Windyo** [comment]
Alright. With family ATM so won't look at it in a super reactive manner but I swear I will. In the meantime you might want to look at themes that ship with Ghosthunter by default to see how they do it. I'll update when I get to to testing your issue. Cheers and merry holidays

Anon Ymous

________________________________

**Comment by twigs67** [comment]
For whenever you get around to it...

I was able to get it initialized by simply restarting the Ghost server, but now I'm getting the following error:

```
TypeError: Cannot read property 'query' of null
    at Object.<anonymous> (jquery.ghosthunter.js?v=956ba85540:3425)
```

It looks like it's not picking up any of my posts under loadApi(). It might be worth noting that I'm using nginx to route to the ghost server and have added '/blog/' prefix to my package.json url.

**Comment by Windyo** [comment]
OK I'm back but my PC fried.
I'll look at this tomorrow.
I see you've set up default.hbs correctly from a cursory glance. I'll put this on my own ghost instance and see what's going on.
