### ISSUE TITLE
Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by Laul0** [jamalneufeld/ghostHunter#72]
Hi,

I'm occurring an error with the JS script but this error is "random".
Sometime, I have to refresh several times the page or the search input sometimes it works directly.
I didn't debug entirely, lack of time, so I provide a screenshot `line 3428` and more informations if necessary.

![screenshot 2018-12-29 at 19 37 14](https://user-images.githubusercontent.com/15279205/50541237-8fb2a300-0ba1-11e9-9ec5-4082c278ca4b.png)

Thx

**Comment by Windyo** [comment]
Probably using onpageload and focusing the search before the index is fully initialized.

But the core reason is just you're trying to use search with an unfinished index.

Anon Ymous

________________________________

**Comment by Windyo** [comment]
Hey, just a quick notification that I'll go ahead and close this next week if there's no update by then.

**Comment by Laul0** [comment]
This issue still true !
I'm trying to understand what I can do to fix it but for the moment with no success 😢

**Comment by melissamcewen** [comment]
I have this issue in Chrome but not Firefox...and some users say it works in Chrome.

**Comment by Nikitozz13** [comment]
I have encountered the same issue but without "random" - it's permanent issue so I can't retrieve results

**Comment by TheBinaryGuy** [comment]
Hey, any update on this?

**Comment by kdyzm** [comment]
Is this the same problem?
![image](https://user-images.githubusercontent.com/12097910/57202733-65537500-6fdb-11e9-90c9-4d7df6da2dbf.png)

**Comment by TheBinaryGuy** [comment]
Yeah, I think so.

**Comment by Laul0** [comment]
Hi @kdyzm, ensure that your first error have not an impact with the ghostHunter.
If you can fix your first error and the second one persist, then yes, you have certainly the same error

**Comment by jpmacor** [comment]
I'm getting a null error in firefox, but a 401 unauthorized in Chrome on the v2 API for ghost:
![image](https://user-images.githubusercontent.com/2495828/57470456-79eb7380-724e-11e9-894b-a813312fe0b9.png)
The null error is tracing to the same line as the first post here. This is the 401 on a get request in chrome:
![image](https://user-images.githubusercontent.com/2495828/57470532-ac956c00-724e-11e9-84c2-e395db4d7265.png)

Oddly the results return fine in Chrome for me, but in no version of Firefox (tested on iPhone as well). The JS does update div elements in Firefox when I empty the search string and have 0 results. I have SAYT enabled, so that 401 in chrome is only when i click in the search field, as I start typing I get no errors, and the results are displayed properly.

**Comment by Laul0** [comment]
Hi, I think I found a solution 🙂🎉🥳

Currently, the solution that I'll show you works on my side for Chrome, Safari and Firefox (you can check yourself here: http://blog.lsonline.fr/search/)

Because the indexing is not executed before the search, I forced the indexation by adding manually:
```javascript
var searchPage = $('#search-field-page').ghostHunter({
    onPageLoad: true,
    ...
```
_Even if into the documentation is mentioned that should be performed automatically (maybe a bug?)_

> When set `true`, posts are checked and indexed when a page is loaded. Early versions of ghostHunter default behavior was to initiate indexing when focus fell in the search field, to reduce the time required for initial page loads.
With caching and other changes, this is no longer needed, and this option can safely be set to `true` always.
> 
> Default value is `true`.


And, to avoid my visitors to search before the end of the indexation, I used the suggestion from the documentation:
```javascript
indexing_start: function() {
    $('.search-field')
        .prop('disabled', true)
        .addClass('yellow-bg')
        .prop('placeholder', 'Indexing, please wait');
},
indexing_end: function() {
    $('.search-field')
        .prop('placeholder', 'Search …')
        .removeClass('yellow-bg')
        .prop('disabled', false);
}
```

Hoping that will help you 🙂

**Comment by kdyzm** [comment]
> Hi, I think I found a solution 🥳
> 
> Currently, the solution that I'll show you works on my side for Chrome, Safari and Firefox (you can check yourself here: http://blog.lsonline.fr/search/)
> 
> Because the indexing is not executed before the search, I forced the indexation by adding manually:
> 
> ```js
> var searchPage = $('#search-field-page').ghostHunter({
>     onPageLoad: true,
>     ...
> ```
> 
> _Even if into the documentation is mentioned that should be performed automatically (maybe a bug?)_
> 
> > When set `true`, posts are checked and indexed when a page is loaded. Early versions of ghostHunter default behavior was to initiate indexing when focus fell in the search field, to reduce the time required for initial page loads.
> > With caching and other changes, this is no longer needed, and this option can safely be set to `true` always.
> > Default value is `true`.
> 
> And, to avoid my visitors to search before the end of the indexation, I used the suggestion from the documentation:
> 
> ```js
> indexing_start: function() {
>     $('.search-field')
>         .prop('disabled', true)
>         .addClass('yellow-bg')
>         .prop('placeholder', 'Indexing, please wait');
> },
> indexing_end: function() {
>     $('.search-field')
>         .prop('placeholder', 'Search …')
>         .removeClass('yellow-bg')
>         .prop('disabled', false);
> }
> ```
> 
> Hoping that will help you

What is your ghost version? I used docker to deploy, the ghost version number is 2.20.1, and I have been reporting "ghost is not defind". I don't know how to solve it. Do you have any way to solve it?
My website is http://blog.kdyzm.cn

**Comment by Laul0** [comment]
Currently, I am using 2.22.3.

I didn't change ghostHuner since several previous versions. I'm using docker to deploy my blog too.

I looked on your site but I didn't find your search page to try it I saw that you have a 404 error with `valine.min.js`.

**Comment by kdyzm** [comment]
> Currently, I am using 2.22.3.
> 
> I didn't change ghostHuner since several previous versions. I'm using docker to deploy my blog too.
> 
> I looked on your site but I didn't find your search page to try it I saw that you have a 404 error with `valine.min.js`.

Thank you for your help, everything has changed after upgrading ghost hunters. It seems that there is new code merged to master branch today, it works for me
