### ISSUE TITLE
Plans to support v2 Content API?

### ISSUE THREAD

**Issue by SteveWooding** [jamalneufeld/ghostHunter#73]
Hi,

Are there any plans to support the new Ghost v2 Content API that replaces the old Public API? At the moment I get the "ghost is undefined" error.

Cheers,

Steve.

**Comment by Windyo** [comment]
Wow is that new? I'll need to look into it .

Anon Ymous

________________________________

**Comment by SteveWooding** [comment]
Yes, more details here:

* https://docs.ghost.org/faq/api-versioning/

Seems to be still some confusion about the status of v2, in my mind. Some places they stay it's stable, others that it's beta still. They have removed the "Enable Ghost API" option from Ghost Admin and switched to setting the API version in the `package.json` file (for the hbs templates). But when I tried setting the version to v0.1, not even basic `{{#get}}` works in the templates. So I'm stuck using v2 on a new install (unless they can tell me a way I can make v0.1 work again).

Here is a link to some basic documentation for the new Javascript client for Content API (v2):

* https://docs.ghost.org/api/javascript/

**Comment by Windyo** [comment]
Huh.

I'll have to look into it. I still have a few issues open as well. But my PC fried a couple of weeks back still waiting to get it back.

I'll research a bit and check it out.

Thanks.

Anon Ymous

________________________________

**Comment by JiapengLi** [comment]
Below patch works for me. 
``` patch
diff --git a/dist/jquery.ghosthunter.js b/dist/jquery.ghosthunter.js
index fd32fba..aa481bf 100644
--- a/dist/jquery.ghosthunter.js
+++ b/dist/jquery.ghosthunter.js
@@ -3152,13 +3152,13 @@ lunr.QueryParser.parseBoost = function (parser) {
 
 		//Here we use jQuery's extend to set default values if they weren't set by the user
 		var opts 		= $.extend( {}, $.fn.ghostHunter.defaults, options );
-		if( opts.results ) 
+		if( opts.results )
 		{
 			pluginMethods.init( this , opts );
 			return pluginMethods;
 		}
 	};
-	 
+
 	// If the Ghost instance is in a subpath of the site, set subpath
 	// as the path to the site with a leading slash and no trailing slash
 	// (i.e. "/path/to/instance").
@@ -3202,7 +3202,7 @@ lunr.QueryParser.parseBoost = function (parser) {
 			this.setAttribute('id', newAttr);
 		});
 	};
-	
+
 	var updateSearchList = function(listItems, apiData, steps) {
 		for (var i=0,ilen=steps.length;i<ilen;i++) {
 			var step = steps[i];
@@ -3232,20 +3232,26 @@ lunr.QueryParser.parseBoost = function (parser) {
 		// console.log('ghostHunter: grabAndIndex');
 		this.blogData = {};
 		this.latestPost = 0;
+		var url = "/ghost/api/v2/content/posts/?key=" + ghosthunter_key + "&limit=all&include=tags";
+
 		var params = {
 			limit: "all",
 			include: "tags",
 		};
 		if ( this.includebodysearch ){
 			params.formats=["plaintext"]
+			url += "&formats=plaintext"
 		} else {
 			params.formats=[""]
 		}
 		if ( this.includepages ){
 			params.filter="(page:true,page:false)";
+			url += "&filter=page:true"
 		}
+
 		var me = this;
-		$.get(ghost.url.api('posts',params)).done(function(data){
+		//$.get(ghost.url.api('posts',params)).done(function(data){
+		$.get(url).done(function(data){
 			var idxSrc = data.posts;
 			// console.log("ghostHunter: indexing all posts")
 			me.index = lunr(function () {
@@ -3389,8 +3395,14 @@ lunr.QueryParser.parseBoost = function (parser) {
 					filter: "updated_at:>\'" + this.latestPost.replace(/\..*/, "").replace(/T/, " ") + "\'",
 					fields: "id"
 				};
+
+				var url = "/ghost/api/v2/content/posts/?key=" +
+				ghosthunter_key + "&limit=all&fields=id" + "&filter" +
+				"updated_at:>\'" + this.latestPost.replace(/\..*/, "").replace(/T/, " ") + "\'";
+
 				var me = this;
-				$.get(ghost.url.api('posts', params)).done(function(data){
+				$.get(url).done(function(data){
+				//$.get(ghost.url.api('posts', params)).done(function(data){
 					if (data.posts.length > 0) {
 						grabAndIndex.call(me);
 					} else {

```
Need define below `ghosthunter_key` in code injection blog header. The key is configured through Integrations.
```html
<script>
    var ghosthunter_key = 'ee7d014d67aaff1b51e054e673';
</script>
```

**Comment by SteveWooding** [comment]
Thanks @JiapengLi. I can confirm that this patch works very nicely indeed.

**Comment by Conor-Burns** [comment]
hey I tried to do this, but i could't get it to work.
what would be the exact procedure to do this?

**Comment by SteveWooding** [comment]
I recommend applying the changes manually to `/dist/jquery.ghosthunter.js` file. It isn't that many lines. The first two changes are just removing trailing spaces. With the other changes, replace the red lines with the green. Then set the Ghost API key (create a new custom integration in the Integrations section of Ghost Admin).

**Comment by Conor-Burns** [comment]
Thanks for your fast reply :D I tried that but sadly it didn't work guess I'll wait...Am 21.02.2019 00:08 schrieb Steven Wooding <notifications@github.com>:I recommend applying the changes manually to /dist/jquery.ghosthunter.js file. It isn't that many lines. The first two changes are just removing trailing spaces. With the other changes, replace the red lines with the green. Then set the Ghost API key (create a new custom integration in the Integrations section of Ghost Admin).

**Comment by cadoo** [comment]
One thing that should be removed from @JiapengLi code is this line:
`url += "&filter=page:true"`

Pages and posts are different URLs in v2 content API (https://docs.ghost.org/api/content/#endpoints).
