### ISSUE TITLE
getting posts url is hardcoded

### ISSUE THREAD

**Issue by ramonskie** [jamalneufeld/ghostHunter#79]
these paths are hardcoded
https://github.com/jamalneufeld/ghostHunter/blob/master/dist/jquery.ghosthunter.js#L3232
https://github.com/jamalneufeld/ghostHunter/blob/master/dist/jquery.ghosthunter.js#L3390

my blog is hosted under `domain.com/blog`
and it tries to reach `domain.com/ghost*` instead of `domain.com/blog/ghost*`

**Comment by trojanh** [comment]
@ramonskie this is fixed in this PR
https://github.com/jamalneufeld/ghostHunter/pull/82
