### ISSUE TITLE
Only searching recent posts

### ISSUE THREAD

**Issue by leemunroe** [jamalneufeld/ghostHunter#8]
Thanks for this solution. Was very straight forward to integrate.

We've implement it on our [blog](http://blog.mailgun.com) however it only seems to be searching recent posts (~15). Assuming this is because looking at the RSS feed it only loads so many posts.

Is there any way to have it search all our posts?

**Comment by hopkinschris** [comment]
@leemunroe @MaluNoPeleke i've written a quick extension to `jquery.ghosthunter.js` because of this specific reason... take a look at the [gist](https://gist.github.com/hopkinschris/5fbfdb1a0ee6412ca62a). i'm not completely happy with it, hence no pull request. feel free to scour it :)

**Comment by Windyo** [comment]
Closed as a duplicate from #7. Let me know if you encounter any other problems.
