### ISSUE TITLE
ghost v3 support

### ISSUE THREAD

**Issue by dbauszus-glx** [jamalneufeld/ghostHunter#80]
We are fairly new to the ghost world and just setup a hosted ghost(pro) blog. This is running ghost v3. Has the ghosthunter plugin be tested with ghost v3? Anything I should consider for the setup?

**Comment by Windyo** [comment]
Hey I'll be honest I haven't maintained this actively for a while.
The latest commits changed the API query format to comply with the public release of API v1 si unless there were big changes this should work as expected.

Anon

________________________________

**Comment by dbauszus-glx** [comment]
No worries. I just setup [ghost-search](https://github.com/HauntedThemes/ghost-search) which updated last week for v3.

I can see why you didn't maintain this. Digging into the ghost structure reveals quite a few frustrating quirks.
