### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Happyfeet01** [jamalneufeld/ghostHunter#84]
Hello, 

Would use your Script for Ghost.
Already setup in Ghost, but get no Searchresult. The Browser Debugger tells me an Security Policy is not correct and jquery is definied.
<img width="624" alt="jquery" src="https://user-images.githubusercontent.com/3295104/70223856-8edca680-174c-11ea-8d79-317a58fa70e0.png">

`			return t.replace(/{{([^{}]*)}}/g, function (a, b) {
				var r = d[b];
				return typeof r === 'string' || typeof r === 'number' ? r : a;
			});
		}
	}

})( jQuery );`

**Comment by Windyo** [comment]
jquery isn't defined, meaning your jquery injection isn't working. fix that :)
