### ISSUE TITLE
MOBILE ONLY - Uncaught TypeError: Cannot read property 'query' of null

### ISSUE THREAD

**Issue by klein09** [jamalneufeld/ghostHunter#85]
I am having issue with the search function only on mobile, "Uncaught TypeError: Cannot read property 'query' of null".

Note: this works in desktop :(

**Comment by klein09** [comment]
I already have this code :( 

<script>
        var ghosthunter_key = 'MY KEY'; 
        $("#search-field").ghostHunter({
          results: "#search-results",
          onKeyUp : true,
          onPageLoad : true
        });
    </script>

**Comment by Windyo** [comment]
probably your them doesn't submit the query properly in it smobile version. Check with the theme developer, sorry I can't help more
